//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetwheels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uetwheels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_black_sports_car_with_the_license_plate_on_the_front___Premium_AI_generated_PSD {
            get {
                object obj = ResourceManager.GetObject("A black sports car with the license plate on the front _ Premium AI-generated PSD" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_black_sports_car_with_the_license_plate_on_the_front___Premium_AI_generated_PSD_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("A_black_sports_car_with_the_license_plate_on_the_front___Premium_AI-generated_PSD" +
                        "-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_black_sports_car_with_the_license_plate_on_the_front___Premium_AI_generated_PSD_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("A_black_sports_car_with_the_license_plate_on_the_front___Premium_AI-generated_PSD" +
                        "-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Money_Bag_SVG___Cash_Dollars_Finance_Wealth_Money_Sack_Printable_Clip_Art_Cut_File__Instant_Download__Commercial_Use__svg_png_jpg_eps_pdf_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Money_Bag_SVG_-_Cash_Dollars_Finance_Wealth_Money_Sack_Printable_Clip_Art_Cut_Fil" +
                        "e__Instant_Download__Commercial_Use__svg_png_jpg_eps_pdf-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User_icon_png_vector___Pixsector__Free_vector_images__mockups__PSDs_and_photos_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("User_icon_png_vector_-_Pixsector__Free_vector_images__mockups__PSDs_and_photos-re" +
                        "movebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User_Icon_Vector_Illustration_In_Glyph_Style_For_Any_Purpose_PNG_Images___Icon__Illustration__Template_PNG_Transparent_Background___Pngtree_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("User_Icon_Vector_Illustration_In_Glyph_Style_For_Any_Purpose_PNG_Images___Icon__I" +
                        "llustration__Template_PNG_Transparent_Background_-_Pngtree-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User_Icon_Vector_Illustration_In_Glyph_Style_For_Any_Purpose_PNG_Images___Icon__Illustration__Template_PNG_Transparent_Background___Pngtree_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("User_Icon_Vector_Illustration_In_Glyph_Style_For_Any_Purpose_PNG_Images___Icon__I" +
                        "llustration__Template_PNG_Transparent_Background_-_Pngtree-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
